### ISSUE TITLE
Error:  Not found

### ISSUE THREAD

**Issue by soly2014** [Knawat/knawat-npm-javascript-sdk#65]
Trace: 
`  Error: https://registry.yarnpkg.com/@kanwat%2fmp: Not found
`when i run 
`yarn add @kanwat/mp`

**Comment by ismail9k** [comment]
Hi @soly2014, 
What version of yarn you are using? also, could you try npm/pnpm and check if you are getting the same error?

**Comment by soly2014** [comment]
@ismail9k fixed by removing the `node_modules` folder
